-- Intel Local Video AI MVP - SQLite schema (Phase 0 skeleton).
-- All timestamps are unix epoch seconds (INTEGER).

PRAGMA foreign_keys = ON;

-- Chat / analysis sessions.
CREATE TABLE IF NOT EXISTS sessions (
    session_id        TEXT PRIMARY KEY,
    title             TEXT,
    current_video_id  TEXT,
    pending_clarification TEXT,           -- nullable: outstanding clarification question
    created_at        INTEGER NOT NULL,
    updated_at        INTEGER NOT NULL,
    FOREIGN KEY (current_video_id) REFERENCES videos(video_id) ON DELETE SET NULL
);

-- Persisted chat messages.
CREATE TABLE IF NOT EXISTS chat_messages (
    message_id  TEXT PRIMARY KEY,
    session_id  TEXT NOT NULL,
    role        TEXT NOT NULL,            -- 'user' | 'assistant' | 'system'
    content     TEXT NOT NULL,
    created_at  INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

-- Local videos associated with sessions.
CREATE TABLE IF NOT EXISTS videos (
    video_id    TEXT PRIMARY KEY,
    session_id  TEXT NOT NULL,
    video_path  TEXT NOT NULL,           -- absolute local path
    duration_seconds REAL,
    width       INTEGER,
    height      INTEGER,
    fps         REAL,
    created_at  INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE
);

-- Cached analysis results per video (transcript, objects, ocr, graphs, etc.).
CREATE TABLE IF NOT EXISTS video_analysis (
    analysis_id   TEXT PRIMARY KEY,
    video_id      TEXT NOT NULL,
    analysis_type TEXT NOT NULL,         -- 'transcript' | 'objects' | 'ocr' | 'graphs' | 'visual_summary'
    result_json   TEXT NOT NULL,         -- JSON-encoded result payload
    created_at    INTEGER NOT NULL,
    FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE CASCADE
);

-- Files generated by report agents (PDF / PPTX / etc.).
CREATE TABLE IF NOT EXISTS generated_files (
    file_id     TEXT PRIMARY KEY,
    session_id  TEXT NOT NULL,
    video_id    TEXT,
    file_type   TEXT NOT NULL,           -- 'pdf' | 'pptx' | ...
    file_path   TEXT NOT NULL,           -- absolute local path under backend/outputs
    created_at  INTEGER NOT NULL,
    FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
    FOREIGN KEY (video_id) REFERENCES videos(video_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_session ON chat_messages(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_videos_session ON videos(session_id);
CREATE INDEX IF NOT EXISTS idx_video_analysis_video ON video_analysis(video_id, analysis_type);
CREATE INDEX IF NOT EXISTS idx_generated_files_session ON generated_files(session_id, created_at);
